### ISSUE TITLE
Fix subscription error

### ISSUE THREAD

**Issue by dreikanter** [logux/logux-rack#20]
There is a subscription error in `master` (1.0.0 is not yet released).

```
npx @logux/backend-test http://localhost:3000/logux

Protocol version: 4
Secret:           parole
Logux server:     http://localhost:31337/
Back-end server:  http://localhost:3000/logux

✔  0 Supports token authentication
✔  1 Supports cookie authentication
✔  2 Processes an error during the authentication
✔  3 Detects wrong token
✔  4 Detects wrong cookie
✔  5 Sends server subprotocol
✔  6 Checks users subprotocol
✔  7 Checks subscription access
✔  8 Checks action access
✔  9 Processes an error during the action processing
✔ 10 Processes an error during the subscription
✖ 11 Processes subscriptions

  Server sent {"type":"users/name","payload":{"userId":"10","name":"B"}}, instead of {"type":"users/name","payload":{"userId":"10","name":"Name"}} action

Test:      file:///Users/dreikanter/amplifr/logux-rack/tests/backend-test/node_modules/@logux/backend-test/tests/actions.js:53:3
Re-run it: npx @logux/backend-test http://localhost:3000/logux 11
```

**Comment by dreikanter** [comment]
Also it makes sense to add integration test to the CI GitHub action workflow.

**Comment by dreikanter** [comment]
Something like this (need to support bidirectional communication between `test` and `server` services):

```yaml
version: '3.4'

services:
  # Development environment
  app:
    image: ruby:2
    environment:
      - BUNDLE_PATH=/bundle
    command: bash
    working_dir: /app
    volumes:
      - .:/app:cached
      - bundle:/bundle
    tmpfs:
      - /tmp

  # Integration test
  test:
    image: node:16
    working_dir: /app
    volumes:
      - ./test:/app:cached
      - test_node_modules:/node_modules
    depends_on:
      - server
    ports:
      - "31337:31337"
    command: bash -c "yarn && npx @logux/backend-test http://server:3000/logux"

  # Ruby on Rails application for integration testing
  server:
    image: ruby:2
    environment:
      - BUNDLE_PATH=/bundle
    working_dir: /app
    volumes:
      - ./test/app:/app:cached
      - .:/logux-rack:cached
      - server_bundle:/bundle
    ports:
      - "3000:3000"
    command: bash -c "bundle && bundle exec rails db:reset && bundle exec rails server"

volumes:
  bundle:
  server_bundle:
  test_bundle:
  test_node_modules:
```
